image:
  repository: 192.168.56.13:80/vue-project/frontend
  tag: latest

# ★ 추가: Harbor 인증 시크릿 정의
imagePullSecrets:
  - name: harbor-registry-secret

deployment:
  timestamp: "none"

service:
  service: LoadBalancer
  port: 80
  loadBalancerIP: "192.168.56.202"